### ISSUE TITLE
Language autodétection

### ISSUE THREAD

**Issue by TiavinaRakotobe** [martinkr/next-export-i18n#9]
Hello, looking at the code and implementing it, and I wonder if there is a language autodetection feature because it always takes my defaultLang as language despite the French language on the browser for example.
Thanks

**Comment by martinkr** [comment]
Hi TiavinaRakotobe,

thank you for your contribution.

Currently there is no auto detection. I'm acutally implenting a feature which checks if there is a langage pack which matches the browser language and uses this as default language.

Hopefully, it will be available next week.

Cheers!

**Comment by TiavinaRakotobe** [comment]
@martinkr thank you for your instant response

**Comment by martinkr** [comment]
Implemented in v1.3.0

- https://github.com/martinkr/next-export-i18n/releases/tag/v1.3.0
- https://www.npmjs.com/package/next-export-i18n/v/1.3.0

Cheers!

**Comment by laymonage** [comment]
@martinkr Is there an option to disable this? I'd like to enforce the default language regardless of the user's browser settings. Some languages aren't available on browsers (or they came preinstalled with English and users do not know how to change it).

**Comment by martinkr** [comment]
Hi @laymonage,

Thank you for reaching out. 
Currently no. You could use the previous version (1.2.x).

I'm not sure I understand you concern, can you elaborate on your issue?
Maybe it's just a misunderstanding.

Let me guide you through the implementation:
1.) you define all available translations of your code
2.) you define the default language for your translation (the one which is used in case the user did not select anything)
3.) the package reads the browser language settings and checks if it is available in your translations (step 1) ). If it is, use this one instead of the default language you specified( step 2). Otherwise - the browser's default lang is not available in the translations - use the default language you set initially (step 2)

Cheers!

**Comment by martinkr** [comment]
Hi @laymonage,

I see! Thank you for the explanation - going to implement the option next week. 
Until then, please use 1.2.x.

Cheers!

**Comment by laymonage** [comment]
No rush, and thank you very much for the useful package!
